### PR TITLE
Fix division by zero bug when using SoapySDR and add build instructions for Ubuntu 19.04

### PR DESCRIPTION
**Pull request by bkerler**
Added build instructions for Ubuntu 19.04

### CODE REVIEW

**Comment by bkerler** [comment]
This fix addresses the issue if frequency is set before samplerate, resulting in fref to be zero, thus the application will crash
due to division by zero in liblms7002m.c, function lms7_pll_calc.

**Comment by chemeris** [comment]
Please split the pull requests into documentation and bugfix.

For the documentation, I don't think it makes sense to have detailed build instructions for all libraries here in libxtrx.

**Comment by bkerler** [comment]
Ok, will do.

**Comment by chemeris** [comment]
And for each bug please submit a separate pull request.

**Pull request closed without merging**
